version: "3.1"
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: apptrading
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default
  www:
    build: .
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    links:
      - db
    networks:
      - default
  phpmyadmin:
    links:
      - db:db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      MYSQL_USERNAME: root
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default
volumes:
  persistent:
