<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class StartMigration extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        // SIDE TRADE
        Schema::dropIfExists('sides');
        Schema::create('sides', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('abbr');
            $table->timestamps();
        });

        $sides = [
            ['name' => 'Buy', 'abbr' => 'B'],
            ['name' => 'Sell', 'abbr' => 'S']
        ];
        foreach ($sides as $side) {
            \App\Side::create($side);}


        // STRATEGIES
        Schema::dropIfExists('strategies');
        Schema::create('strategies', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('description')->nullable();
            $table->foreignId('user_id')->constrained();
            $table->timestamps();
        });

        // MOODS
        Schema::dropIfExists('moods');
        Schema::create('moods', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('icon')->nullable();
            $table->timestamps();
        });

        $moods = [
            ['name' => 'Happy'],
            ['name' => 'Sad'],
            ['name' => 'Relaxed'],
            ['name' => 'Excited'],
        ];

        foreach ($moods as $mood) {\App\Mood::create($mood);}

        // MARKETS
        Schema::dropIfExists('markets');
        Schema::create('markets', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('description')->nullable();
            $table->timestamps();
        });
        $markets = [
            ['name' => 'Forex'],
            ['name' => 'Commodities'],
            ['name' => 'Indices'],
            ['name' => 'Stocks'],
            ['name' => 'Cryptos'],
            ['name' => 'Bonds'],
            ['name' => 'Futures'],
        ];

        foreach ($markets as $market) {
            \App\Market::create($market);}

        // ASSETS
        Schema::dropIfExists('assets');
        Schema::create('assets', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->bigIncrements('id');
            $table->foreignId('market_id')->constrained();
            $table->string('name');
            $table->string('abbr')->nullable();
            $table->double('tick')->nullable();
            $table->string('description')->nullable();
            $table->timestamps();
        });

        $assets = [
            //FUTURES
            [ 'abbr' => '', 'name' => 'Ibex', 'market_id' => 7, 'tick' => 1],
            [ 'abbr' => '', 'name' => 'Mini-Ibex', 'market_id' => 7, 'tick' => 5 ],
            [ 'abbr' => '', 'name' => 'Dax', 'market_id' => 7, 'tick' => 0.5 ],
            [ 'abbr' => '', 'name' => 'Mini-Dax', 'market_id' => 7, 'tick' => 1 ],
            [ 'abbr' => '', 'name' => 'Eurostoxx', 'market_id' => 7, 'tick' => 1 ],
            [ 'abbr' => 'ES', 'name' => 'E-mini S&P 500', 'market_id' => 7, 'tick' => 0.25 ],
            [ 'abbr' => 'MES', 'name' => 'E-micro S&P 500', 'market_id' => 7, 'tick' => 0.25 ],
            [ 'abbr' => 'NQ', 'name' => 'E-mini Nasdaq', 'market_id' => 7, 'tick' => 0.25 ],
            [ 'abbr' => 'MNQ', 'name' => 'Micro E-mini Nasdaq', 'market_id' => 7, 'tick' => 0.25 ],
            [ 'abbr' => '', 'name' => 'E-mini Dow Jones', 'market_id' => 7, 'tick' => 1 ],
            [ 'abbr' => '', 'name' => 'Micro E-mini Dow Jones', 'market_id' => 7, 'tick' => 1 ],
            [ 'abbr' => 'CL', 'name' => 'Petroleo', 'market_id' => 7, 'tick' => 0.01 ],
            [ 'abbr' => 'QM', 'name' => 'E-mini Petroleo', 'market_id' => 7, 'tick' => 0.025 ],
            [ 'abbr' => '6E', 'name' => 'EUR/USD', 'market_id' => 7, 'tick' => 0.00005 ],

            //FOREX
            [ 'abbr' => 'AUDCAD', 'name' => 'AUD/CAD', 'market_id' => 1 ],
            [ 'abbr' => 'AUDCHF', 'name' => 'AUD/CHF', 'market_id' => 1 ],
            [ 'abbr' => 'AUDJPY', 'name' => 'AUD/JPY', 'market_id' => 1 ],
            [ 'abbr' => 'AUDNZD', 'name' => 'AUD/NZD', 'market_id' => 1 ],
            [ 'abbr' => 'AUDUSD', 'name' => 'AUD/USD', 'market_id' => 1 ],
            [ 'abbr' => 'BGNRON', 'name' => 'BGN/RON', 'market_id' => 1 ],
            [ 'abbr' => 'CADCHF', 'name' => 'CAD/CHF', 'market_id' => 1 ],
            [ 'abbr' => 'CADJPY', 'name' => 'CAD/JPY', 'market_id' => 1 ],
            [ 'abbr' => 'CHFBGN', 'name' => 'CHF/BGN', 'market_id' => 1 ],
            [ 'abbr' => 'CHFJPY', 'name' => 'CHF/JPY', 'market_id' => 1 ],
            [ 'abbr' => 'CHFRON', 'name' => 'CHF/RON', 'market_id' => 1 ],
            [ 'abbr' => 'CHFTRY', 'name' => 'CHF/TRY', 'market_id' => 1 ],
            [ 'abbr' => 'EURAUD', 'name' => 'EUR/AUD', 'market_id' => 1 ],
            [ 'abbr' => 'EURCAD', 'name' => 'EUR/CAD', 'market_id' => 1 ],
            [ 'abbr' => 'EURCHF', 'name' => 'EUR/CHF', 'market_id' => 1 ],
            [ 'abbr' => 'EURCZK', 'name' => 'EUR/CZK', 'market_id' => 1 ],
            [ 'abbr' => 'EURDKK', 'name' => 'EUR/DKK', 'market_id' => 1 ],
            [ 'abbr' => 'EURGBP', 'name' => 'EUR/GBP', 'market_id' => 1 ],
            [ 'abbr' => 'EURHKD', 'name' => 'EUR/HKD', 'market_id' => 1 ],
            [ 'abbr' => 'EURHUF', 'name' => 'EUR/HUF', 'market_id' => 1 ],
            [ 'abbr' => 'EURILS', 'name' => 'EUR/ILS', 'market_id' => 1 ],
            [ 'abbr' => 'EURJPY', 'name' => 'EUR/JPY', 'market_id' => 1 ],
            [ 'abbr' => 'EURMXN', 'name' => 'EUR/MXN', 'market_id' => 1 ],
            [ 'abbr' => 'EURNOK', 'name' => 'EUR/NOK', 'market_id' => 1 ],
            [ 'abbr' => 'EURNZD', 'name' => 'EUR/NZD', 'market_id' => 1 ],
            [ 'abbr' => 'EURPLN', 'name' => 'EUR/PLN', 'market_id' => 1 ],
            [ 'abbr' => 'EURRON', 'name' => 'EUR/RON', 'market_id' => 1 ],
            [ 'abbr' => 'EURRUB', 'name' => 'EUR/RUB', 'market_id' => 1 ],
            [ 'abbr' => 'EURSEK', 'name' => 'EUR/SEK', 'market_id' => 1 ],
            [ 'abbr' => 'EURSGD', 'name' => 'EUR/SGD', 'market_id' => 1 ],
            [ 'abbr' => 'EURTRY', 'name' => 'EUR/TRY', 'market_id' => 1 ],
            [ 'abbr' => 'EURUSD', 'name' => 'EUR/USD', 'market_id' => 1 ],
            [ 'abbr' => 'EURZAR', 'name' => 'EUR/ZAR', 'market_id' => 1 ],
            [ 'abbr' => 'GBPAUD', 'name' => 'GBP/AUD', 'market_id' => 1 ],
            [ 'abbr' => 'GBPBGN', 'name' => 'GBP/BGN', 'market_id' => 1 ],
            [ 'abbr' => 'GBPCAD', 'name' => 'GBP/CAD', 'market_id' => 1 ],
            [ 'abbr' => 'GBPCHF', 'name' => 'GBP/CHF', 'market_id' => 1 ],
            [ 'abbr' => 'GBPCZK', 'name' => 'GBP/CZK', 'market_id' => 1 ],
            [ 'abbr' => 'GBPDKK', 'name' => 'GBP/DKK', 'market_id' => 1 ],
            [ 'abbr' => 'GBPHKD', 'name' => 'GBP/HKD', 'market_id' => 1 ],
            [ 'abbr' => 'GBPHUF', 'name' => 'GBP/HUF', 'market_id' => 1 ],
            [ 'abbr' => 'GBPJPY', 'name' => 'GBP/JPY', 'market_id' => 1 ],
            [ 'abbr' => 'GBPNOK', 'name' => 'GBP/NOK', 'market_id' => 1 ],
            [ 'abbr' => 'GBPNZD', 'name' => 'GBP/NZD', 'market_id' => 1 ],
            [ 'abbr' => 'GBPPLN', 'name' => 'GBP/PLN', 'market_id' => 1 ],
            [ 'abbr' => 'GBPRON', 'name' => 'GBP/RON', 'market_id' => 1 ],
            [ 'abbr' => 'GBPSEK', 'name' => 'GBP/SEK', 'market_id' => 1 ],
            [ 'abbr' => 'GBPSGD', 'name' => 'GBP/SGD', 'market_id' => 1 ],
            [ 'abbr' => 'GBPTRY', 'name' => 'GBP/TRY', 'market_id' => 1 ],
            [ 'abbr' => 'GBPUSD', 'name' => 'GBP/USD', 'market_id' => 1 ],
            [ 'abbr' => 'GBPZAR', 'name' => 'GBP/ZAR', 'market_id' => 1 ],
            [ 'abbr' => 'HKDJPY', 'name' => 'HKD/JPY', 'market_id' => 1 ],
            [ 'abbr' => 'NZDCAD', 'name' => 'NZD/CAD', 'market_id' => 1 ],
            [ 'abbr' => 'NZDCHF', 'name' => 'NZD/CHF', 'market_id' => 1 ],
            [ 'abbr' => 'NZDJPY', 'name' => 'NZD/JPY', 'market_id' => 1 ],
            [ 'abbr' => 'NZDUSD', 'name' => 'NZD/USD', 'market_id' => 1 ],
            [ 'abbr' => 'SGDHKD', 'name' => 'SGD/HKD', 'market_id' => 1 ],
            [ 'abbr' => 'SGDJPY', 'name' => 'SGD/JPY', 'market_id' => 1 ],
            [ 'abbr' => 'TRYBGN', 'name' => 'TRY/BGN', 'market_id' => 1 ],
            [ 'abbr' => 'TRYJPY', 'name' => 'TRY/JPY', 'market_id' => 1 ],
            [ 'abbr' => 'TRYRON', 'name' => 'TRY/RON', 'market_id' => 1 ],
            [ 'abbr' => 'USDBGN', 'name' => 'USD/BGN', 'market_id' => 1 ],
            [ 'abbr' => 'USDCAD', 'name' => 'USD/CAD', 'market_id' => 1 ],
            [ 'abbr' => 'USDCHF', 'name' => 'USD/CHF', 'market_id' => 1 ],
            [ 'abbr' => 'USDCZK', 'name' => 'USD/CZK', 'market_id' => 1 ],
            [ 'abbr' => 'USDDKK', 'name' => 'USD/DKK', 'market_id' => 1 ],
            [ 'abbr' => 'USDHKD', 'name' => 'USD/HKD', 'market_id' => 1 ],
            [ 'abbr' => 'USDHUF', 'name' => 'USD/HUF', 'market_id' => 1 ],
            [ 'abbr' => 'USDILS', 'name' => 'USD/ILS', 'market_id' => 1 ],
            [ 'abbr' => 'USDJPY', 'name' => 'USD/JPY', 'market_id' => 1 ],
            [ 'abbr' => 'USDMXN', 'name' => 'USD/MXN', 'market_id' => 1 ],
            [ 'abbr' => 'USDNOK', 'name' => 'USD/NOK', 'market_id' => 1 ],
            [ 'abbr' => 'USDPLN', 'name' => 'USD/PLN', 'market_id' => 1 ],
            [ 'abbr' => 'USDRON', 'name' => 'USD/RON', 'market_id' => 1 ],
            [ 'abbr' => 'USDRUB', 'name' => 'USD/RUB', 'market_id' => 1 ],
            [ 'abbr' => 'USDSEK', 'name' => 'USD/SEK', 'market_id' => 1 ],
            [ 'abbr' => 'USDSGD', 'name' => 'USD/SGD', 'market_id' => 1 ],
            [ 'abbr' => 'USDTRY', 'name' => 'USD/TRY', 'market_id' => 1 ],
            [ 'abbr' => 'USDZAR', 'name' => 'USD/ZAR', 'market_id' => 1 ],
            [ 'abbr' => 'USDCOP', 'name' => 'USD/COP', 'market_id' => 1 ],
            [ 'abbr' => 'GOLD', 'name' => 'GOLD', 'market_id' => 1 ],

            //COMMODITIES
            [ 'abbr' => 'GC', 'name' => 'Gold', 'market_id' => 2 ],
            [ 'abbr' => 'WTI', 'name' => 'WTI Crude Oil', 'market_id' => 2 ],
            [ 'abbr' => 'BRENT', 'name' => 'Brent Crude', 'market_id' => 2 ],
            [ 'abbr' => 'ET', 'name' => 'Ethanol', 'market_id' => 2 ],
            [ 'abbr' => 'NG', 'name' => 'Natural gas', 'market_id' => 2 ],
            [ 'abbr' => 'SI', 'name' => 'Silver', 'market_id' => 2 ],
            [ 'abbr' => 'QS', 'name' => 'Gasoil', 'market_id' => 2 ],
            [ 'abbr' => 'XPT', 'name' => 'Platinum', 'market_id' => 2 ],
            [ 'abbr' => 'KC', 'name' => 'Coffee', 'market_id' => 2 ],
            [ 'abbr' => 'HG', 'name' => 'Copper', 'market_id' => 2 ],
            [ 'abbr' => 'CN', 'name' => 'Corn', 'market_id' => 2 ],
            [ 'abbr' => 'W', 'name' => 'Wheat', 'market_id' => 2 ],
            [ 'abbr' => 'CT', 'name' => 'Cotton', 'market_id' => 2 ],

            //INDICES
            [ 'abbr' => 'SP500', 'name' => 'S&P 500', 'market_id' => 3 ],
            [ 'abbr' => 'DJI', 'name' => 'Dow 30', 'market_id' => 3 ],
            [ 'abbr' => 'ND', 'name' => 'Nasdaq', 'market_id' => 3 ],
            [ 'abbr' => 'DAX', 'name' => 'DAX', 'market_id' => 3 ],
            [ 'abbr' => 'NK', 'name' => 'Nikkei 225', 'market_id' => 3 ],
            [ 'abbr' => 'SX5E', 'name' => 'Euro Stoxx 50', 'market_id' => 3 ],
            [ 'abbr' => 'FTSE', 'name' => 'FTSE 100', 'market_id' => 3 ],
            [ 'abbr' => 'IBOV', 'name' => 'Bovespa', 'market_id' => 3 ],
            [ 'abbr' => 'COLCAP', 'name' => 'COLCAP', 'market_id' => 3 ],
            [ 'abbr' => 'DXY', 'name' => 'Dollar Index', 'market_id' => 3 ],
            [ 'abbr' => 'VIX', 'name' => 'Volatility Index', 'market_id' => 3 ],

            //STOCKS
            [ 'abbr' => 'MMM', 'name' => '3M Company', 'market_id' => 4 ],
            [ 'abbr' => 'ABT', 'name' => 'Abbott Laboratories', 'market_id' => 4 ],
            [ 'abbr' => 'ABBV', 'name' => 'AbbVie Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'ABMD', 'name' => 'ABIOMED Inc', 'market_id' => 4 ],
            [ 'abbr' => 'ACN', 'name' => 'Accenture plc', 'market_id' => 4 ],
            [ 'abbr' => 'ATVI', 'name' => 'Activision Blizzard', 'market_id' => 4 ],
            [ 'abbr' => 'ADBE', 'name' => 'Adobe Systems Inc', 'market_id' => 4 ],
            [ 'abbr' => 'AMD', 'name' => 'Advanced Micro Devices Inc', 'market_id' => 4 ],
            [ 'abbr' => 'AAP', 'name' => 'Advance Auto Parts', 'market_id' => 4 ],
            [ 'abbr' => 'AES', 'name' => 'AES Corp', 'market_id' => 4 ],
            [ 'abbr' => 'AMG', 'name' => 'Affiliated Managers Group Inc', 'market_id' => 4 ],
            [ 'abbr' => 'AFL', 'name' => 'AFLAC Inc', 'market_id' => 4 ],
            [ 'abbr' => 'A', 'name' => 'Agilent Technologies Inc', 'market_id' => 4 ],
            [ 'abbr' => 'APD', 'name' => 'Air Products & Chemicals Inc', 'market_id' => 4 ],
            [ 'abbr' => 'AKAM', 'name' => 'Akamai Technologies Inc', 'market_id' => 4 ],
            [ 'abbr' => 'ALK', 'name' => 'Alaska Air Group Inc', 'market_id' => 4 ],
            [ 'abbr' => 'ALB', 'name' => 'Albemarle Corp', 'market_id' => 4 ],
            [ 'abbr' => 'ARE', 'name' => 'Alexandria Real Estate Equities', 'market_id' => 4 ],
            [ 'abbr' => 'ALXN', 'name' => 'Alexion Pharmaceuticals', 'market_id' => 4 ],
            [ 'abbr' => 'ALGN', 'name' => 'Align Technology', 'market_id' => 4 ],
            [ 'abbr' => 'ALLE', 'name' => 'Allegion', 'market_id' => 4 ],
            [ 'abbr' => 'AGN', 'name' => 'Allergan Plc', 'market_id' => 4 ],
            [ 'abbr' => 'ADS', 'name' => 'Alliance Data Systems', 'market_id' => 4 ],
            [ 'abbr' => 'LNT', 'name' => 'Alliant Energy Corp', 'market_id' => 4 ],
            [ 'abbr' => 'ALL', 'name' => 'Allstate Corp', 'market_id' => 4 ],
            [ 'abbr' => 'GOOGL', 'name' => 'Alphabet Inc Class A', 'market_id' => 4 ],
            [ 'abbr' => 'GOOG', 'name' => 'Alphabet Inc Class C', 'market_id' => 4 ],
            [ 'abbr' => 'MO', 'name' => 'Altria Group Inc', 'market_id' => 4 ],
            [ 'abbr' => 'AMZN', 'name' => 'Amazon.com Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'AMCR', 'name' => 'Amcor plc', 'market_id' => 4 ],
            [ 'abbr' => 'AEE', 'name' => 'Ameren Corp', 'market_id' => 4 ],
            [ 'abbr' => 'AAL', 'name' => 'American Airlines Group', 'market_id' => 4 ],
            [ 'abbr' => 'AEP', 'name' => 'American Electric Power', 'market_id' => 4 ],
            [ 'abbr' => 'AXP', 'name' => 'American Express Co', 'market_id' => 4 ],
            [ 'abbr' => 'AIG', 'name' => 'American International Group', 'market_id' => 4 ],
            [ 'abbr' => 'AMT', 'name' => 'American Tower Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'AWK', 'name' => 'American Water Works Company Inc', 'market_id' => 4 ],
            [ 'abbr' => 'AMP', 'name' => 'Ameriprise Financial', 'market_id' => 4 ],
            [ 'abbr' => 'ABC', 'name' => 'AmerisourceBergen Corp', 'market_id' => 4 ],
            [ 'abbr' => 'AME', 'name' => 'AMETEK Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'AMGN', 'name' => 'Amgen Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'APH', 'name' => 'Amphenol Corp', 'market_id' => 4 ],
            [ 'abbr' => 'ADI', 'name' => 'Analog Devices Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'ANSS', 'name' => 'ANSYS', 'market_id' => 4 ],
            [ 'abbr' => 'ANTM', 'name' => 'Anthem', 'market_id' => 4 ],
            [ 'abbr' => 'AON', 'name' => 'Aon plc', 'market_id' => 4 ],
            [ 'abbr' => 'AOS', 'name' => 'A.O. Smith Corp', 'market_id' => 4 ],
            [ 'abbr' => 'APA', 'name' => 'Apache Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'AIV', 'name' => 'Apartment Investment & Management', 'market_id' => 4 ],
            [ 'abbr' => 'AAPL', 'name' => 'Apple Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'AMAT', 'name' => 'Applied Materials Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'APTV', 'name' => 'Aptiv Plc', 'market_id' => 4 ],
            [ 'abbr' => 'ADM', 'name' => 'Archer-Daniels-Midland Co', 'market_id' => 4 ],
            [ 'abbr' => 'ARNC', 'name' => 'Arconic Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'ANET', 'name' => 'Arista Networks', 'market_id' => 4 ],
            [ 'abbr' => 'AJG', 'name' => 'Arthur J. Gallagher & Co.', 'market_id' => 4 ],
            [ 'abbr' => 'AIZ', 'name' => 'Assurant', 'market_id' => 4 ],
            [ 'abbr' => 'ATO', 'name' => 'Atmos Energy Corp', 'market_id' => 4 ],
            [ 'abbr' => 'T', 'name' => 'AT&T Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'ADSK', 'name' => 'Autodesk Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'ADP', 'name' => 'Automatic Data Processing', 'market_id' => 4 ],
            [ 'abbr' => 'AZO', 'name' => 'AutoZone Inc', 'market_id' => 4 ],
            [ 'abbr' => 'AVB', 'name' => 'AvalonBay Communities Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'AVY', 'name' => 'Avery Dennison Corp', 'market_id' => 4 ],
            [ 'abbr' => 'BKR', 'name' => 'Baker Hughes Co', 'market_id' => 4 ],
            [ 'abbr' => 'BLL', 'name' => 'Ball Corp', 'market_id' => 4 ],
            [ 'abbr' => 'BAC', 'name' => 'Bank of America Corp', 'market_id' => 4 ],
            [ 'abbr' => 'BK', 'name' => 'The Bank of New York Mellon Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'BAX', 'name' => 'Baxter International Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'BBT', 'name' => 'BB&T Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'BDX', 'name' => 'Becton Dickinson', 'market_id' => 4 ],
            [ 'abbr' => 'BRK.B', 'name' => 'Berkshire Hathaway', 'market_id' => 4 ],
            [ 'abbr' => 'BBY', 'name' => 'Best Buy Co. Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'BIIB', 'name' => 'Biogen Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'BLK', 'name' => 'BlackRock', 'market_id' => 4 ],
            [ 'abbr' => 'HRB', 'name' => 'Block H&R', 'market_id' => 4 ],
            [ 'abbr' => 'BA', 'name' => 'Boeing Company', 'market_id' => 4 ],
            [ 'abbr' => 'BKNG', 'name' => 'Booking Holdings Inc', 'market_id' => 4 ],
            [ 'abbr' => 'BWA', 'name' => 'BorgWarner', 'market_id' => 4 ],
            [ 'abbr' => 'BXP', 'name' => 'Boston Properties', 'market_id' => 4 ],
            [ 'abbr' => 'BSX', 'name' => 'Boston Scientific', 'market_id' => 4 ],
            [ 'abbr' => 'BMY', 'name' => 'Bristol-Myers Squibb', 'market_id' => 4 ],
            [ 'abbr' => 'AVGO', 'name' => 'Broadcom Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'BR', 'name' => 'Broadridge Financial Solutions', 'market_id' => 4 ],
            [ 'abbr' => 'BF.B', 'name' => 'Brown-Forman Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'CHRW', 'name' => 'C. H. Robinson Worldwide', 'market_id' => 4 ],
            [ 'abbr' => 'COG', 'name' => 'Cabot Oil & Gas', 'market_id' => 4 ],
            [ 'abbr' => 'CDNS', 'name' => 'Cadence Design Systems', 'market_id' => 4 ],
            [ 'abbr' => 'CPB', 'name' => 'Campbell Soup', 'market_id' => 4 ],
            [ 'abbr' => 'COF', 'name' => 'Capital One Financial', 'market_id' => 4 ],
            [ 'abbr' => 'CPRI', 'name' => 'Capri Holdings', 'market_id' => 4 ],
            [ 'abbr' => 'CAH', 'name' => 'Cardinal Health Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'KMX', 'name' => 'Carmax Inc', 'market_id' => 4 ],
            [ 'abbr' => 'CCL', 'name' => 'Carnival Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'CAT', 'name' => 'Caterpillar Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'CBOE', 'name' => 'Cboe Global Markets', 'market_id' => 4 ],
            [ 'abbr' => 'CBRE', 'name' => 'CBRE Group', 'market_id' => 4 ],
            [ 'abbr' => 'CBS', 'name' => 'CBS Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'CDW', 'name' => 'CDW', 'market_id' => 4 ],
            [ 'abbr' => 'CE', 'name' => 'Celanese', 'market_id' => 4 ],
            [ 'abbr' => 'CELG', 'name' => 'Celgene Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'CNC', 'name' => 'Centene Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'CNP', 'name' => 'CenterPoint Energy', 'market_id' => 4 ],
            [ 'abbr' => 'CTL', 'name' => 'CenturyLink Inc', 'market_id' => 4 ],
            [ 'abbr' => 'CERN', 'name' => 'Cerner', 'market_id' => 4 ],
            [ 'abbr' => 'CF', 'name' => 'CF Industries Holdings Inc', 'market_id' => 4 ],
            [ 'abbr' => 'SCHW', 'name' => 'Charles Schwab Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'CHTR', 'name' => 'Charter Communications', 'market_id' => 4 ],
            [ 'abbr' => 'CVX', 'name' => 'Chevron Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'CMG', 'name' => 'Chipotle Mexican Grill', 'market_id' => 4 ],
            [ 'abbr' => 'CB', 'name' => 'Chubb Limited', 'market_id' => 4 ],
            [ 'abbr' => 'CHD', 'name' => 'Church & Dwight', 'market_id' => 4 ],
            [ 'abbr' => 'CI', 'name' => 'CIGNA Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'XEC', 'name' => 'Cimarex Energy', 'market_id' => 4 ],
            [ 'abbr' => 'CINF', 'name' => 'Cincinnati Financial', 'market_id' => 4 ],
            [ 'abbr' => 'CTAS', 'name' => 'Cintas Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'CSCO', 'name' => 'Cisco Systems', 'market_id' => 4 ],
            [ 'abbr' => 'C', 'name' => 'Citigroup Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'CFG', 'name' => 'Citizens Financial Group', 'market_id' => 4 ],
            [ 'abbr' => 'CTXS', 'name' => 'Citrix Systems', 'market_id' => 4 ],
            [ 'abbr' => 'CLX', 'name' => 'The Clorox Company', 'market_id' => 4 ],
            [ 'abbr' => 'CME', 'name' => 'CME Group Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'CMS', 'name' => 'CMS Energy', 'market_id' => 4 ],
            [ 'abbr' => 'KO', 'name' => 'Coca-Cola Company', 'market_id' => 4 ],
            [ 'abbr' => 'CTSH', 'name' => 'Cognizant Technology Solutions', 'market_id' => 4 ],
            [ 'abbr' => 'CL', 'name' => 'Colgate-Palmolive', 'market_id' => 4 ],
            [ 'abbr' => 'CMCSA', 'name' => 'Comcast Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'CMA', 'name' => 'Comerica Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'CAG', 'name' => 'Conagra Brands', 'market_id' => 4 ],
            [ 'abbr' => 'CXO', 'name' => 'Concho Resources', 'market_id' => 4 ],
            [ 'abbr' => 'COP', 'name' => 'ConocoPhillips', 'market_id' => 4 ],
            [ 'abbr' => 'ED', 'name' => 'Consolidated Edison', 'market_id' => 4 ],
            [ 'abbr' => 'STZ', 'name' => 'Constellation Brands', 'market_id' => 4 ],
            [ 'abbr' => 'COO', 'name' => 'The Cooper Companies', 'market_id' => 4 ],
            [ 'abbr' => 'CPRT', 'name' => 'Copart Inc', 'market_id' => 4 ],
            [ 'abbr' => 'GLW', 'name' => 'Corning Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'CTVA', 'name' => 'Corteva', 'market_id' => 4 ],
            [ 'abbr' => 'COST', 'name' => 'Costco Wholesale Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'COTY', 'name' => 'Coty Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'CCI', 'name' => 'Crown Castle International Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'CSX', 'name' => 'CSX Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'CMI', 'name' => 'Cummins Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'CVS', 'name' => 'CVS Health', 'market_id' => 4 ],
            [ 'abbr' => 'DHI', 'name' => 'D. R. Horton', 'market_id' => 4 ],
            [ 'abbr' => 'DHR', 'name' => 'Danaher Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'DRI', 'name' => 'Darden Restaurants', 'market_id' => 4 ],
            [ 'abbr' => 'DVA', 'name' => 'DaVita Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'DE', 'name' => 'Deere & Co.', 'market_id' => 4 ],
            [ 'abbr' => 'DAL', 'name' => 'Delta Air Lines Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'XRAY', 'name' => 'Dentsply Sirona', 'market_id' => 4 ],
            [ 'abbr' => 'DVN', 'name' => 'Devon Energy', 'market_id' => 4 ],
            [ 'abbr' => 'FANG', 'name' => 'Diamondback Energy', 'market_id' => 4 ],
            [ 'abbr' => 'DLR', 'name' => 'Digital Realty Trust Inc', 'market_id' => 4 ],
            [ 'abbr' => 'DFS', 'name' => 'Discover Financial Services', 'market_id' => 4 ],
            [ 'abbr' => 'DISCA', 'name' => 'Discovery Inc. Class A', 'market_id' => 4 ],
            [ 'abbr' => 'DISCK', 'name' => 'Discovery Inc. Class C', 'market_id' => 4 ],
            [ 'abbr' => 'DISH', 'name' => 'Dish Network', 'market_id' => 4 ],
            [ 'abbr' => 'DG', 'name' => 'Dollar General', 'market_id' => 4 ],
            [ 'abbr' => 'DLTR', 'name' => 'Dollar Tree', 'market_id' => 4 ],
            [ 'abbr' => 'D', 'name' => 'Dominion Energy', 'market_id' => 4 ],
            [ 'abbr' => 'DOV', 'name' => 'Dover Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'DOW', 'name' => 'Dow Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'DTE', 'name' => 'DTE Energy Co.', 'market_id' => 4 ],
            [ 'abbr' => 'DUK', 'name' => 'Duke Energy', 'market_id' => 4 ],
            [ 'abbr' => 'DRE', 'name' => 'Duke Realty Corp', 'market_id' => 4 ],
            [ 'abbr' => 'DD', 'name' => 'DuPont de Nemours Inc', 'market_id' => 4 ],
            [ 'abbr' => 'DXC', 'name' => 'DXC Technology', 'market_id' => 4 ],
            [ 'abbr' => 'ETFC', 'name' => 'E*Trade', 'market_id' => 4 ],
            [ 'abbr' => 'EMN', 'name' => 'Eastman Chemical', 'market_id' => 4 ],
            [ 'abbr' => 'ETN', 'name' => 'Eaton Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'EBAY', 'name' => 'eBay Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'ECL', 'name' => 'Ecolab Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'EIX', 'name' => 'Edison Int\'l', 'market_id' => 4 ],
            [ 'abbr' => 'EW', 'name' => 'Edwards Lifesciences', 'market_id' => 4 ],
            [ 'abbr' => 'EA', 'name' => 'Electronic Arts', 'market_id' => 4 ],
            [ 'abbr' => 'EMR', 'name' => 'Emerson Electric Company', 'market_id' => 4 ],
            [ 'abbr' => 'ETR', 'name' => 'Entergy Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'EOG', 'name' => 'EOG Resources', 'market_id' => 4 ],
            [ 'abbr' => 'EFX', 'name' => 'Equifax Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'EQIX', 'name' => 'Equinix', 'market_id' => 4 ],
            [ 'abbr' => 'EQR', 'name' => 'Equity Residential', 'market_id' => 4 ],
            [ 'abbr' => 'ESS', 'name' => 'Essex Property Trust Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'EL', 'name' => 'Estee Lauder Cos.', 'market_id' => 4 ],
            [ 'abbr' => 'EVRG', 'name' => 'Evergy', 'market_id' => 4 ],
            [ 'abbr' => 'ES', 'name' => 'Eversource Energy', 'market_id' => 4 ],
            [ 'abbr' => 'RE', 'name' => 'Everest Re Group Ltd.', 'market_id' => 4 ],
            [ 'abbr' => 'EXC', 'name' => 'Exelon Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'EXPE', 'name' => 'Expedia Group', 'market_id' => 4 ],
            [ 'abbr' => 'EXPD', 'name' => 'Expeditors', 'market_id' => 4 ],
            [ 'abbr' => 'EXR', 'name' => 'Extra Space Storage', 'market_id' => 4 ],
            [ 'abbr' => 'XOM', 'name' => 'Exxon Mobil Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'FFIV', 'name' => 'F5 Networks', 'market_id' => 4 ],
            [ 'abbr' => 'FB', 'name' => 'Facebook Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'FAST', 'name' => 'Fastenal Co', 'market_id' => 4 ],
            [ 'abbr' => 'FRT', 'name' => 'Federal Realty Investment Trust', 'market_id' => 4 ],
            [ 'abbr' => 'FDX', 'name' => 'FedEx Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'FIS', 'name' => 'Fidelity National Information Services', 'market_id' => 4 ],
            [ 'abbr' => 'FITB', 'name' => 'Fifth Third Bancorp', 'market_id' => 4 ],
            [ 'abbr' => 'FE', 'name' => 'FirstEnergy Corp', 'market_id' => 4 ],
            [ 'abbr' => 'FRC', 'name' => 'First Republic Bank', 'market_id' => 4 ],
            [ 'abbr' => 'FISV', 'name' => 'Fiserv Inc', 'market_id' => 4 ],
            [ 'abbr' => 'FLT', 'name' => 'FleetCor Technologies Inc', 'market_id' => 4 ],
            [ 'abbr' => 'FLIR', 'name' => 'FLIR Systems', 'market_id' => 4 ],
            [ 'abbr' => 'FLS', 'name' => 'Flowserve Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'FMC', 'name' => 'FMC Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'F', 'name' => 'Ford Motor', 'market_id' => 4 ],
            [ 'abbr' => 'FTNT', 'name' => 'Fortinet', 'market_id' => 4 ],
            [ 'abbr' => 'FTV', 'name' => 'Fortive Corp', 'market_id' => 4 ],
            [ 'abbr' => 'FBHS', 'name' => 'Fortune Brands Home & Security', 'market_id' => 4 ],
            [ 'abbr' => 'FOXA', 'name' => 'Fox Corporation Class A', 'market_id' => 4 ],
            [ 'abbr' => 'FOX', 'name' => 'Fox Corporation Class B', 'market_id' => 4 ],
            [ 'abbr' => 'BEN', 'name' => 'Franklin Resources', 'market_id' => 4 ],
            [ 'abbr' => 'FCX', 'name' => 'Freeport-McMoRan Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'GPS', 'name' => 'Gap Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'GRMN', 'name' => 'Garmin Ltd.', 'market_id' => 4 ],
            [ 'abbr' => 'IT', 'name' => 'Gartner Inc', 'market_id' => 4 ],
            [ 'abbr' => 'GD', 'name' => 'General Dynamics', 'market_id' => 4 ],
            [ 'abbr' => 'GE', 'name' => 'General Electric', 'market_id' => 4 ],
            [ 'abbr' => 'GIS', 'name' => 'General Mills', 'market_id' => 4 ],
            [ 'abbr' => 'GM', 'name' => 'General Motors', 'market_id' => 4 ],
            [ 'abbr' => 'GPC', 'name' => 'Genuine Parts', 'market_id' => 4 ],
            [ 'abbr' => 'GILD', 'name' => 'Gilead Sciences', 'market_id' => 4 ],
            [ 'abbr' => 'GL', 'name' => 'Globe Life Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'GPN', 'name' => 'Global Payments Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'GS', 'name' => 'Goldman Sachs Group', 'market_id' => 4 ],
            [ 'abbr' => 'GWW', 'name' => 'Grainger (W.W.) Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'HAL', 'name' => 'Halliburton Co.', 'market_id' => 4 ],
            [ 'abbr' => 'HBI', 'name' => 'Hanesbrands Inc', 'market_id' => 4 ],
            [ 'abbr' => 'HOG', 'name' => 'Harley-Davidson', 'market_id' => 4 ],
            [ 'abbr' => 'HIG', 'name' => 'Hartford Financial Svc.Gp.', 'market_id' => 4 ],
            [ 'abbr' => 'HAS', 'name' => 'Hasbro Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'HCA', 'name' => 'HCA Healthcare', 'market_id' => 4 ],
            [ 'abbr' => 'PEAK', 'name' => 'Healthpeak Properties', 'market_id' => 4 ],
            [ 'abbr' => 'HP', 'name' => 'Helmerich & Payne', 'market_id' => 4 ],
            [ 'abbr' => 'HSIC', 'name' => 'Henry Schein', 'market_id' => 4 ],
            [ 'abbr' => 'HSY', 'name' => 'The Hershey Company', 'market_id' => 4 ],
            [ 'abbr' => 'HES', 'name' => 'Hess Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'HPE', 'name' => 'Hewlett Packard Enterprise', 'market_id' => 4 ],
            [ 'abbr' => 'HLT', 'name' => 'Hilton Worldwide Holdings Inc', 'market_id' => 4 ],
            [ 'abbr' => 'HFC', 'name' => 'HollyFrontier Corp', 'market_id' => 4 ],
            [ 'abbr' => 'HOLX', 'name' => 'Hologic', 'market_id' => 4 ],
            [ 'abbr' => 'HD', 'name' => 'Home Depot', 'market_id' => 4 ],
            [ 'abbr' => 'HON', 'name' => 'Honeywell Int\'l Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'HRL', 'name' => 'Hormel Foods Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'HST', 'name' => 'Host Hotels & Resorts', 'market_id' => 4 ],
            [ 'abbr' => 'HPQ', 'name' => 'HP Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'HUM', 'name' => 'Humana Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'HBAN', 'name' => 'Huntington Bancshares', 'market_id' => 4 ],
            [ 'abbr' => 'HII', 'name' => 'Huntington Ingalls Industries', 'market_id' => 4 ],
            [ 'abbr' => 'IEX', 'name' => 'IDEX Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'IDXX', 'name' => 'IDEXX Laboratories', 'market_id' => 4 ],
            [ 'abbr' => 'INFO', 'name' => 'IHS Markit Ltd.', 'market_id' => 4 ],
            [ 'abbr' => 'ITW', 'name' => 'Illinois Tool Works', 'market_id' => 4 ],
            [ 'abbr' => 'ILMN', 'name' => 'Illumina Inc', 'market_id' => 4 ],
            [ 'abbr' => 'IR', 'name' => 'Ingersoll-Rand PLC', 'market_id' => 4 ],
            [ 'abbr' => 'INTC', 'name' => 'Intel Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'ICE', 'name' => 'Intercontinental Exchange', 'market_id' => 4 ],
            [ 'abbr' => 'IBM', 'name' => 'International Business Machines', 'market_id' => 4 ],
            [ 'abbr' => 'INCY', 'name' => 'Incyte', 'market_id' => 4 ],
            [ 'abbr' => 'IP', 'name' => 'International Paper', 'market_id' => 4 ],
            [ 'abbr' => 'IPG', 'name' => 'Interpublic Group', 'market_id' => 4 ],
            [ 'abbr' => 'IFF', 'name' => 'Intl Flavors & Fragrances', 'market_id' => 4 ],
            [ 'abbr' => 'INTU', 'name' => 'Intuit Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'ISRG', 'name' => 'Intuitive Surgical Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'IVZ', 'name' => 'Invesco Ltd.', 'market_id' => 4 ],
            [ 'abbr' => 'IPGP', 'name' => 'IPG Photonics Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'IQV', 'name' => 'IQVIA Holdings Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'IRM', 'name' => 'Iron Mountain Incorporated', 'market_id' => 4 ],
            [ 'abbr' => 'JKHY', 'name' => 'Jack Henry & Associates', 'market_id' => 4 ],
            [ 'abbr' => 'JEC', 'name' => 'Jacobs Engineering Group', 'market_id' => 4 ],
            [ 'abbr' => 'JBHT', 'name' => 'J. B. Hunt Transport Services', 'market_id' => 4 ],
            [ 'abbr' => 'SJM', 'name' => 'JM Smucker', 'market_id' => 4 ],
            [ 'abbr' => 'JNJ', 'name' => 'Johnson & Johnson', 'market_id' => 4 ],
            [ 'abbr' => 'JCI', 'name' => 'Johnson Controls International', 'market_id' => 4 ],
            [ 'abbr' => 'JPM', 'name' => 'JPMorgan Chase & Co.', 'market_id' => 4 ],
            [ 'abbr' => 'JNPR', 'name' => 'Juniper Networks', 'market_id' => 4 ],
            [ 'abbr' => 'KSU', 'name' => 'Kansas City Southern', 'market_id' => 4 ],
            [ 'abbr' => 'K', 'name' => 'Kellogg Co.', 'market_id' => 4 ],
            [ 'abbr' => 'KEY', 'name' => 'KeyCorp', 'market_id' => 4 ],
            [ 'abbr' => 'KEYS', 'name' => 'Keysight Technologies', 'market_id' => 4 ],
            [ 'abbr' => 'KMB', 'name' => 'Kimberly-Clark', 'market_id' => 4 ],
            [ 'abbr' => 'KIM', 'name' => 'Kimco Realty', 'market_id' => 4 ],
            [ 'abbr' => 'KMI', 'name' => 'Kinder Morgan', 'market_id' => 4 ],
            [ 'abbr' => 'KLAC', 'name' => 'KLA Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'KSS', 'name' => 'Kohl\'s Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'KHC', 'name' => 'Kraft Heinz Co', 'market_id' => 4 ],
            [ 'abbr' => 'KR', 'name' => 'Kroger Co.', 'market_id' => 4 ],
            [ 'abbr' => 'LB', 'name' => 'L Brands Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'LHX', 'name' => 'L3Harris Technologies', 'market_id' => 4 ],
            [ 'abbr' => 'LH', 'name' => 'Laboratory Corp. of America Holding', 'market_id' => 4 ],
            [ 'abbr' => 'LRCX', 'name' => 'Lam Research', 'market_id' => 4 ],
            [ 'abbr' => 'LW', 'name' => 'Lamb Weston Holdings Inc', 'market_id' => 4 ],
            [ 'abbr' => 'LVS', 'name' => 'Las Vegas Sands Corp', 'market_id' => 4 ],
            [ 'abbr' => 'LEG', 'name' => 'Leggett & Platt', 'market_id' => 4 ],
            [ 'abbr' => 'LDOS', 'name' => 'Leidos Holdings', 'market_id' => 4 ],
            [ 'abbr' => 'LEN', 'name' => 'Lennar Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'LLY', 'name' => 'Lilly (Eli) & Co.', 'market_id' => 4 ],
            [ 'abbr' => 'LNC', 'name' => 'Lincoln National', 'market_id' => 4 ],
            [ 'abbr' => 'LIN', 'name' => 'Linde plc', 'market_id' => 4 ],
            [ 'abbr' => 'LKQ', 'name' => 'LKQ Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'LMT', 'name' => 'Lockheed Martin Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'L', 'name' => 'Loews Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'LOW', 'name' => 'Lowe\'s Cos.', 'market_id' => 4 ],
            [ 'abbr' => 'LYB', 'name' => 'LyondellBasell', 'market_id' => 4 ],
            [ 'abbr' => 'MTB', 'name' => 'M&T Bank Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'MAC', 'name' => 'Macerich', 'market_id' => 4 ],
            [ 'abbr' => 'M', 'name' => 'Macy\'s Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'MRO', 'name' => 'Marathon Oil Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'MPC', 'name' => 'Marathon Petroleum', 'market_id' => 4 ],
            [ 'abbr' => 'MKTX', 'name' => 'MarketAxess', 'market_id' => 4 ],
            [ 'abbr' => 'MAR', 'name' => 'Marriott Int\'l.', 'market_id' => 4 ],
            [ 'abbr' => 'MMC', 'name' => 'Marsh & McLennan', 'market_id' => 4 ],
            [ 'abbr' => 'MLM', 'name' => 'Martin Marietta Materials', 'market_id' => 4 ],
            [ 'abbr' => 'MAS', 'name' => 'Masco Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'MA', 'name' => 'Mastercard Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'MKC', 'name' => 'McCormick & Co.', 'market_id' => 4 ],
            [ 'abbr' => 'MXIM', 'name' => 'Maxim Integrated Products Inc', 'market_id' => 4 ],
            [ 'abbr' => 'MCD', 'name' => 'McDonald\'s Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'MCK', 'name' => 'McKesson Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'MDT', 'name' => 'Medtronic plc', 'market_id' => 4 ],
            [ 'abbr' => 'MRK', 'name' => 'Merck & Co.', 'market_id' => 4 ],
            [ 'abbr' => 'MET', 'name' => 'MetLife Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'MTD', 'name' => 'Mettler Toledo', 'market_id' => 4 ],
            [ 'abbr' => 'MGM', 'name' => 'MGM Resorts International', 'market_id' => 4 ],
            [ 'abbr' => 'MCHP', 'name' => 'Microchip Technology', 'market_id' => 4 ],
            [ 'abbr' => 'MU', 'name' => 'Micron Technology', 'market_id' => 4 ],
            [ 'abbr' => 'MSFT', 'name' => 'Microsoft Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'MAA', 'name' => 'Mid-America Apartments', 'market_id' => 4 ],
            [ 'abbr' => 'MHK', 'name' => 'Mohawk Industries', 'market_id' => 4 ],
            [ 'abbr' => 'TAP', 'name' => 'Molson Coors Brewing Company', 'market_id' => 4 ],
            [ 'abbr' => 'MDLZ', 'name' => 'Mondelez International', 'market_id' => 4 ],
            [ 'abbr' => 'MNST', 'name' => 'Monster Beverage', 'market_id' => 4 ],
            [ 'abbr' => 'MCO', 'name' => 'Moody\'s Corp', 'market_id' => 4 ],
            [ 'abbr' => 'MS', 'name' => 'Morgan Stanley', 'market_id' => 4 ],
            [ 'abbr' => 'MOS', 'name' => 'The Mosaic Company', 'market_id' => 4 ],
            [ 'abbr' => 'MSI', 'name' => 'Motorola Solutions Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'MSCI', 'name' => 'MSCI Inc', 'market_id' => 4 ],
            [ 'abbr' => 'MYL', 'name' => 'Mylan N.V.', 'market_id' => 4 ],
            [ 'abbr' => 'NDAQ', 'name' => 'Nasdaq Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'NOV', 'name' => 'National Oilwell Varco Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'NTAP', 'name' => 'NetApp', 'market_id' => 4 ],
            [ 'abbr' => 'NFLX', 'name' => 'Netflix Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'NWL', 'name' => 'Newell Brands', 'market_id' => 4 ],
            [ 'abbr' => 'NEM', 'name' => 'Newmont Goldcorp', 'market_id' => 4 ],
            [ 'abbr' => 'NWSA', 'name' => 'News Corp. Class A', 'market_id' => 4 ],
            [ 'abbr' => 'NWS', 'name' => 'News Corp. Class B', 'market_id' => 4 ],
            [ 'abbr' => 'NEE', 'name' => 'NextEra Energy', 'market_id' => 4 ],
            [ 'abbr' => 'NLSN', 'name' => 'Nielsen Holdings', 'market_id' => 4 ],
            [ 'abbr' => 'NKE', 'name' => 'Nike', 'market_id' => 4 ],
            [ 'abbr' => 'NI', 'name' => 'NiSource Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'NBL', 'name' => 'Noble Energy Inc', 'market_id' => 4 ],
            [ 'abbr' => 'JWN', 'name' => 'Nordstrom', 'market_id' => 4 ],
            [ 'abbr' => 'NSC', 'name' => 'Norfolk Southern Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'NTRS', 'name' => 'Northern Trust Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'NOC', 'name' => 'Northrop Grumman', 'market_id' => 4 ],
            [ 'abbr' => 'NLOK', 'name' => 'NortonLifeLock', 'market_id' => 4 ],
            [ 'abbr' => 'NCLH', 'name' => 'Norwegian Cruise Line Holdings', 'market_id' => 4 ],
            [ 'abbr' => 'NRG', 'name' => 'NRG Energy', 'market_id' => 4 ],
            [ 'abbr' => 'NUE', 'name' => 'Nucor Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'NVDA', 'name' => 'Nvidia Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'NVR', 'name' => 'NVR Inc', 'market_id' => 4 ],
            [ 'abbr' => 'ORLY', 'name' => 'O\'Reilly Automotive', 'market_id' => 4 ],
            [ 'abbr' => 'OXY', 'name' => 'Occidental Petroleum', 'market_id' => 4 ],
            [ 'abbr' => 'OMC', 'name' => 'Omnicom Group', 'market_id' => 4 ],
            [ 'abbr' => 'OKE', 'name' => 'ONEOK', 'market_id' => 4 ],
            [ 'abbr' => 'ORCL', 'name' => 'Oracle Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'PCAR', 'name' => 'PACCAR Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'PKG', 'name' => 'Packaging Corporation of America', 'market_id' => 4 ],
            [ 'abbr' => 'PH', 'name' => 'Parker-Hannifin', 'market_id' => 4 ],
            [ 'abbr' => 'PAYX', 'name' => 'Paychex Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'PYPL', 'name' => 'PayPal', 'market_id' => 4 ],
            [ 'abbr' => 'PNR', 'name' => 'Pentair plc', 'market_id' => 4 ],
            [ 'abbr' => 'PBCT', 'name' => 'People\'s United Financial', 'market_id' => 4 ],
            [ 'abbr' => 'PEP', 'name' => 'PepsiCo Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'PKI', 'name' => 'PerkinElmer', 'market_id' => 4 ],
            [ 'abbr' => 'PRGO', 'name' => 'Perrigo', 'market_id' => 4 ],
            [ 'abbr' => 'PFE', 'name' => 'Pfizer Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'PM', 'name' => 'Philip Morris International', 'market_id' => 4 ],
            [ 'abbr' => 'PSX', 'name' => 'Phillips 66', 'market_id' => 4 ],
            [ 'abbr' => 'PNW', 'name' => 'Pinnacle West Capital', 'market_id' => 4 ],
            [ 'abbr' => 'PXD', 'name' => 'Pioneer Natural Resources', 'market_id' => 4 ],
            [ 'abbr' => 'PNC', 'name' => 'PNC Financial Services', 'market_id' => 4 ],
            [ 'abbr' => 'PPG', 'name' => 'PPG Industries', 'market_id' => 4 ],
            [ 'abbr' => 'PPL', 'name' => 'PPL Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'PFG', 'name' => 'Principal Financial Group', 'market_id' => 4 ],
            [ 'abbr' => 'PG', 'name' => 'Procter & Gamble', 'market_id' => 4 ],
            [ 'abbr' => 'PGR', 'name' => 'Progressive Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'PLD', 'name' => 'Prologis', 'market_id' => 4 ],
            [ 'abbr' => 'PRU', 'name' => 'Prudential Financial', 'market_id' => 4 ],
            [ 'abbr' => 'PEG', 'name' => 'Public Serv. Enterprise Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'PSA', 'name' => 'Public Storage', 'market_id' => 4 ],
            [ 'abbr' => 'PHM', 'name' => 'Pulte Homes Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'PVH', 'name' => 'PVH Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'QRVO', 'name' => 'Qorvo', 'market_id' => 4 ],
            [ 'abbr' => 'PWR', 'name' => 'Quanta Services Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'QCOM', 'name' => 'QUALCOMM Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'DGX', 'name' => 'Quest Diagnostics', 'market_id' => 4 ],
            [ 'abbr' => 'RL', 'name' => 'Ralph Lauren Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'RJF', 'name' => 'Raymond James Financial Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'RTN', 'name' => 'Raytheon Co.', 'market_id' => 4 ],
            [ 'abbr' => 'O', 'name' => 'Realty Income Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'REG', 'name' => 'Regency Centers Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'REGN', 'name' => 'Regeneron Pharmaceuticals', 'market_id' => 4 ],
            [ 'abbr' => 'RF', 'name' => 'Regions Financial Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'RSG', 'name' => 'Republic Services Inc', 'market_id' => 4 ],
            [ 'abbr' => 'RMD', 'name' => 'ResMed', 'market_id' => 4 ],
            [ 'abbr' => 'RHI', 'name' => 'Robert Half International', 'market_id' => 4 ],
            [ 'abbr' => 'ROK', 'name' => 'Rockwell Automation Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'ROL', 'name' => 'Rollins Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'ROP', 'name' => 'Roper Technologies', 'market_id' => 4 ],
            [ 'abbr' => 'ROST', 'name' => 'Ross Stores', 'market_id' => 4 ],
            [ 'abbr' => 'RCL', 'name' => 'Royal Caribbean Cruises Ltd', 'market_id' => 4 ],
            [ 'abbr' => 'CRM', 'name' => 'Salesforce.com', 'market_id' => 4 ],
            [ 'abbr' => 'SBAC', 'name' => 'SBA Communications', 'market_id' => 4 ],
            [ 'abbr' => 'SLB', 'name' => 'Schlumberger Ltd.', 'market_id' => 4 ],
            [ 'abbr' => 'STX', 'name' => 'Seagate Technology', 'market_id' => 4 ],
            [ 'abbr' => 'SEE', 'name' => 'Sealed Air', 'market_id' => 4 ],
            [ 'abbr' => 'SRE', 'name' => 'Sempra Energy', 'market_id' => 4 ],
            [ 'abbr' => 'SHW', 'name' => 'Sherwin-Williams', 'market_id' => 4 ],
            [ 'abbr' => 'SPG', 'name' => 'Simon Property Group Inc', 'market_id' => 4 ],
            [ 'abbr' => 'SWKS', 'name' => 'Skyworks Solutions', 'market_id' => 4 ],
            [ 'abbr' => 'SLG', 'name' => 'SL Green Realty', 'market_id' => 4 ],
            [ 'abbr' => 'SNA', 'name' => 'Snap-on', 'market_id' => 4 ],
            [ 'abbr' => 'SO', 'name' => 'Southern Co.', 'market_id' => 4 ],
            [ 'abbr' => 'LUV', 'name' => 'Southwest Airlines', 'market_id' => 4 ],
            [ 'abbr' => 'SPGI', 'name' => 'S&P Global Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'SWK', 'name' => 'Stanley Black & Decker', 'market_id' => 4 ],
            [ 'abbr' => 'SBUX', 'name' => 'Starbucks Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'STT', 'name' => 'State Street Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'SYK', 'name' => 'Stryker Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'STI', 'name' => 'SunTrust Banks', 'market_id' => 4 ],
            [ 'abbr' => 'SIVB', 'name' => 'SVB Financial', 'market_id' => 4 ],
            [ 'abbr' => 'SYF', 'name' => 'Synchrony Financial', 'market_id' => 4 ],
            [ 'abbr' => 'SNPS', 'name' => 'Synopsys Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'SYY', 'name' => 'Sysco Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'TMUS', 'name' => 'T-Mobile US', 'market_id' => 4 ],
            [ 'abbr' => 'TROW', 'name' => 'T. Rowe Price Group', 'market_id' => 4 ],
            [ 'abbr' => 'TTWO', 'name' => 'Take-Two Interactive', 'market_id' => 4 ],
            [ 'abbr' => 'TPR', 'name' => 'Tapestry Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'TGT', 'name' => 'Target Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'TEL', 'name' => 'TE Connectivity Ltd.', 'market_id' => 4 ],
            [ 'abbr' => 'FTI', 'name' => 'TechnipFMC', 'market_id' => 4 ],
            [ 'abbr' => 'TFX', 'name' => 'Teleflex', 'market_id' => 4 ],
            [ 'abbr' => 'TXN', 'name' => 'Texas Instruments', 'market_id' => 4 ],
            [ 'abbr' => 'TXT', 'name' => 'Textron Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'TMO', 'name' => 'Thermo Fisher Scientific', 'market_id' => 4 ],
            [ 'abbr' => 'TIF', 'name' => 'Tiffany & Co.', 'market_id' => 4 ],
            [ 'abbr' => 'TWTR', 'name' => 'Twitter Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'TJX', 'name' => 'TJX Companies Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'TSCO', 'name' => 'Tractor Supply Company', 'market_id' => 4 ],
            [ 'abbr' => 'TDG', 'name' => 'TransDigm Group', 'market_id' => 4 ],
            [ 'abbr' => 'TRV', 'name' => 'The Travelers Companies Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'TRIP', 'name' => 'TripAdvisor', 'market_id' => 4 ],
            [ 'abbr' => 'TSN', 'name' => 'Tyson Foods', 'market_id' => 4 ],
            [ 'abbr' => 'UDR', 'name' => 'UDR Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'ULTA', 'name' => 'Ulta Beauty', 'market_id' => 4 ],
            [ 'abbr' => 'USB', 'name' => 'U.S. Bancorp', 'market_id' => 4 ],
            [ 'abbr' => 'UAA', 'name' => 'Under Armour Class A', 'market_id' => 4 ],
            [ 'abbr' => 'UA', 'name' => 'Under Armour Class C', 'market_id' => 4 ],
            [ 'abbr' => 'UNP', 'name' => 'Union Pacific Corp', 'market_id' => 4 ],
            [ 'abbr' => 'UAL', 'name' => 'United Airlines Holdings', 'market_id' => 4 ],
            [ 'abbr' => 'UNH', 'name' => 'United Health Group Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'UPS', 'name' => 'United Parcel Service', 'market_id' => 4 ],
            [ 'abbr' => 'URI', 'name' => 'United Rentals Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'UTX', 'name' => 'United Technologies', 'market_id' => 4 ],
            [ 'abbr' => 'UHS', 'name' => 'Universal Health Services Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'UNM', 'name' => 'Unum Group', 'market_id' => 4 ],
            [ 'abbr' => 'VFC', 'name' => 'V.F. Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'VLO', 'name' => 'Valero Energy', 'market_id' => 4 ],
            [ 'abbr' => 'VAR', 'name' => 'Varian Medical Systems', 'market_id' => 4 ],
            [ 'abbr' => 'VTR', 'name' => 'Ventas Inc', 'market_id' => 4 ],
            [ 'abbr' => 'VRSN', 'name' => 'Verisign Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'VRSK', 'name' => 'Verisk Analytics', 'market_id' => 4 ],
            [ 'abbr' => 'VZ', 'name' => 'Verizon Communications', 'market_id' => 4 ],
            [ 'abbr' => 'VRTX', 'name' => 'Vertex Pharmaceuticals Inc', 'market_id' => 4 ],
            [ 'abbr' => 'VIAB', 'name' => 'Viacom Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'V', 'name' => 'Visa Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'VNO', 'name' => 'Vornado Realty Trust', 'market_id' => 4 ],
            [ 'abbr' => 'VMC', 'name' => 'Vulcan Materials', 'market_id' => 4 ],
            [ 'abbr' => 'WAB', 'name' => 'Wabtec Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'WMT', 'name' => 'Walmart', 'market_id' => 4 ],
            [ 'abbr' => 'WBA', 'name' => 'Walgreens Boots Alliance', 'market_id' => 4 ],
            [ 'abbr' => 'DIS', 'name' => 'The Walt Disney Company', 'market_id' => 4 ],
            [ 'abbr' => 'WM', 'name' => 'Waste Management Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'WAT', 'name' => 'Waters Corporation', 'market_id' => 4 ],
            [ 'abbr' => 'WEC', 'name' => 'Wec Energy Group Inc', 'market_id' => 4 ],
            [ 'abbr' => 'WCG', 'name' => 'WellCare', 'market_id' => 4 ],
            [ 'abbr' => 'WFC', 'name' => 'Wells Fargo', 'market_id' => 4 ],
            [ 'abbr' => 'WELL', 'name' => 'Welltower Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'WDC', 'name' => 'Western Digital', 'market_id' => 4 ],
            [ 'abbr' => 'WU', 'name' => 'Western Union Co', 'market_id' => 4 ],
            [ 'abbr' => 'WRK', 'name' => 'WestRock', 'market_id' => 4 ],
            [ 'abbr' => 'WY', 'name' => 'Weyerhaeuser', 'market_id' => 4 ],
            [ 'abbr' => 'WHR', 'name' => 'Whirlpool Corp.', 'market_id' => 4 ],
            [ 'abbr' => 'WMB', 'name' => 'Williams Cos.', 'market_id' => 4 ],
            [ 'abbr' => 'WLTW', 'name' => 'Willis Towers Watson', 'market_id' => 4 ],
            [ 'abbr' => 'WYNN', 'name' => 'Wynn Resorts Ltd', 'market_id' => 4 ],
            [ 'abbr' => 'XEL', 'name' => 'Xcel Energy Inc', 'market_id' => 4 ],
            [ 'abbr' => 'XRX', 'name' => 'Xerox', 'market_id' => 4 ],
            [ 'abbr' => 'XLNX', 'name' => 'Xilinx', 'market_id' => 4 ],
            [ 'abbr' => 'XYL', 'name' => 'Xylem Inc.', 'market_id' => 4 ],
            [ 'abbr' => 'YUM', 'name' => 'Yum! Brands Inc', 'market_id' => 4 ],
            [ 'abbr' => 'ZBH', 'name' => 'Zimmer Biomet Holdings', 'market_id' => 4 ],
            [ 'abbr' => 'ZION', 'name' => 'Zions Bancorp', 'market_id' => 4 ],
            [ 'abbr' => 'ZTS', 'name' => 'Zoetis', 'market_id' => 4 ],
            [ 'abbr' => 'EXITO', 'name' => 'Almacenes Exito', 'market_id' => 4 ],
            [ 'abbr' => 'PFAVAL', 'name' => 'Aval Acciones y Valores Pref', 'market_id' => 4 ],
            [ 'abbr' => 'PFAVH', 'name' => 'Avianca Pf', 'market_id' => 4 ],
            [ 'abbr' => 'PFDAVVNDA', 'name' => 'Banco Davivienda Pf', 'market_id' => 4 ],
            [ 'abbr' => 'BOGOTA', 'name' => 'Banco De Bogota', 'market_id' => 4 ],
            [ 'abbr' => 'PFBCOLOM', 'name' => 'Bancolombia Pf', 'market_id' => 4 ],
            [ 'abbr' => 'BVC', 'name' => 'Bolsa De Valores De Colombia', 'market_id' => 4 ],
            [ 'abbr' => 'CNEC', 'name' => 'Canacol Energy', 'market_id' => 4 ],
            [ 'abbr' => 'CELSIA', 'name' => 'Celsia', 'market_id' => 4 ],
            [ 'abbr' => 'CEMARGOS', 'name' => 'Cemargos', 'market_id' => 4 ],
            [ 'abbr' => 'PFCEMARGOS', 'name' => 'Cementos Argos Pf', 'market_id' => 4 ],
            [ 'abbr' => 'CLH', 'name' => 'Cemex Latam', 'market_id' => 4 ],
            [ 'abbr' => 'CORFICOLCF', 'name' => 'Corficolombiana', 'market_id' => 4 ],
            [ 'abbr' => 'CONCONCRET', 'name' => 'Conconcret', 'market_id' => 4 ],
            [ 'abbr' => 'ECOPETROL', 'name' => 'Ecopetrol', 'market_id' => 4 ],
            [ 'abbr' => 'ETB', 'name' => 'Etb', 'market_id' => 4 ],
            [ 'abbr' => 'GRUPOARGOS', 'name' => 'Grupo Argos', 'market_id' => 4 ],
            [ 'abbr' => 'PFGRUPOARG', 'name' => 'Grupo Argos Pref', 'market_id' => 4 ],
            [ 'abbr' => 'GEB', 'name' => 'Grupo Energia Bogota', 'market_id' => 4 ],
            [ 'abbr' => 'GRUPOAVAL', 'name' => 'Grupo Aval', 'market_id' => 4 ],
            [ 'abbr' => 'NUTRESA', 'name' => 'Nutresa', 'market_id' => 4 ],
            [ 'abbr' => 'PFGRUPSURA', 'name' => 'Pfgrupsura', 'market_id' => 4 ],
            [ 'abbr' => 'GRUPOSURA', 'name' => 'Suramericana', 'market_id' => 4 ],

            //CRYPTOS
            [ 'abbr' => 'BTC', 'name' => 'Bitcoin', 'market_id' => 5 ],
            [ 'abbr' => 'ETH', 'name' => 'Ethereum', 'market_id' => 5 ],
            [ 'abbr' => 'XRP', 'name' => 'Ripple', 'market_id' => 5 ],
            [ 'abbr' => 'BCH', 'name' => 'Bitcoin Cash', 'market_id' => 5 ],
            [ 'abbr' => 'USDT', 'name' => 'Tether', 'market_id' => 5 ],
            [ 'abbr' => 'LTC', 'name' => 'Litecoin', 'market_id' => 5 ],
            [ 'abbr' => 'EOS', 'name' => 'EOS', 'market_id' => 5 ],
            [ 'abbr' => 'BNB', 'name' => 'Binance Coin', 'market_id' => 5 ],
            [ 'abbr' => 'BSV', 'name' => 'Bitcoin SV', 'market_id' => 5 ],
            [ 'abbr' => 'XLM', 'name' => 'Stellar', 'market_id' => 5 ],
            [ 'abbr' => 'TRX', 'name' => 'TRON', 'market_id' => 5 ],
            [ 'abbr' => 'ADA', 'name' => 'Cardano', 'market_id' => 5 ],
            [ 'abbr' => 'XMR', 'name' => 'Monero', 'market_id' => 5 ],
            [ 'abbr' => 'LEO', 'name' => 'UNUS SED LEO', 'market_id' => 5 ],
            [ 'abbr' => 'LINK', 'name' => 'Chainlink', 'market_id' => 5 ],
            [ 'abbr' => 'HT', 'name' => 'Huobi Token', 'market_id' => 5 ],
            [ 'abbr' => 'NEO', 'name' => 'NEO', 'market_id' => 5 ],
            [ 'abbr' => 'ATOM', 'name' => 'Cosmos', 'market_id' => 5 ],
            [ 'abbr' => 'XTZ', 'name' => 'Tezos', 'market_id' => 5 ],
            [ 'abbr' => 'MIOTA', 'name' => 'IOTA', 'market_id' => 5 ],
            [ 'abbr' => 'MKR', 'name' => 'Maker', 'market_id' => 5 ],
            [ 'abbr' => 'DASH', 'name' => 'Dash', 'market_id' => 5 ],
            [ 'abbr' => 'ETC', 'name' => 'Ethereum Classic', 'market_id' => 5 ],
            [ 'abbr' => 'ONT', 'name' => 'Ontology', 'market_id' => 5 ],
            [ 'abbr' => 'USDC', 'name' => 'USD Coin', 'market_id' => 5 ],
            [ 'abbr' => 'CRO', 'name' => 'Crypto.com Coin', 'market_id' => 5 ],
            [ 'abbr' => 'XEM', 'name' => 'NEM', 'market_id' => 5 ],
            [ 'abbr' => 'INO', 'name' => 'INO COIN', 'market_id' => 5 ],
            [ 'abbr' => 'VET', 'name' => 'VeChain', 'market_id' => 5 ],
            [ 'abbr' => 'DOGE', 'name' => 'Dogecoin', 'market_id' => 5 ],
            [ 'abbr' => 'BAT', 'name' => 'Basic Attention Token', 'market_id' => 5 ],
            [ 'abbr' => 'ZEC', 'name' => 'Zcash', 'market_id' => 5 ],
            [ 'abbr' => 'INB', 'name' => 'Insight Chain', 'market_id' => 5 ],
            [ 'abbr' => 'DCR', 'name' => 'Decred', 'market_id' => 5 ],
            [ 'abbr' => 'PAX', 'name' => 'Paxos Standard', 'market_id' => 5 ],
            [ 'abbr' => 'PZM', 'name' => 'PRIZM', 'market_id' => 5 ],
            [ 'abbr' => 'MEXC', 'name' => 'MEXC Token', 'market_id' => 5 ],
            [ 'abbr' => 'QTUM', 'name' => 'Qtum', 'market_id' => 5 ],
            [ 'abbr' => 'HEDG', 'name' => 'HedgeTrade', 'market_id' => 5 ],
            [ 'abbr' => 'MIN', 'name' => 'MINDOL', 'market_id' => 5 ],
            [ 'abbr' => 'ZRX', 'name' => '0x', 'market_id' => 5 ],
            [ 'abbr' => 'TUSD', 'name' => 'TrueUSD', 'market_id' => 5 ],
            [ 'abbr' => 'THX', 'name' => 'ThoreNext', 'market_id' => 5 ],
            [ 'abbr' => 'HOT', 'name' => 'Holo', 'market_id' => 5 ],
            [ 'abbr' => 'VSYS', 'name' => 'V Systems', 'market_id' => 5 ],
            [ 'abbr' => 'BTG', 'name' => 'Bitcoin Gold', 'market_id' => 5 ],

            //BONDS
            [ 'abbr' => 'UST30Y', 'name' => 'U.S. 30Y', 'market_id' => 6 ],
            [ 'abbr' => 'UST10Y', 'name' => 'U.S. 10Y', 'market_id' => 6 ],
            [ 'abbr' => 'USG5Y', 'name' => 'U.S. 5Y', 'market_id' => 6 ],
            [ 'abbr' => 'USG2Y', 'name' => 'U.S. 2Y', 'market_id' => 6 ],
        ];
        foreach ($assets as $asset) {
            \App\Asset::create($asset);
        }
        // BROKERS
        Schema::dropIfExists('brokers');
        Schema::create('brokers', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->bigIncrements('id');
            $table->string('name');
            $table->timestamps();
        });
        $brokers = [
            ['name' => '24option' ],
            ['name' => '4xCube' ],
            ['name' => 'Alianza Valores' ],
            ['name' => 'Ally Invest' ],
            ['name' => 'Alpari' ],
            ['name' => 'AMP Futures' ],
            ['name' => 'ATFX' ],
            ['name' => 'AvaTrade' ],
            ['name' => 'BCS Forex' ],
            ['name' => 'CapitalXP' ],
            ['name' => 'Casa de Bolsa' ],
            ['name' => 'Charles Schwab' ],
            ['name' => 'City Index' ],
            ['name' => 'CMC Markets' ],
            ['name' => 'CMSTrader' ],
            ['name' => 'Credicorp Capital' ],
            ['name' => 'Davivienda Corredores' ],
            ['name' => 'Dukascopy ' ],
            ['name' => 'E*TRADE' ],
            ['name' => 'EagleFX' ],
            ['name' => 'easyMarkets' ],
            ['name' => 'eOption' ],
            ['name' => 'EverFX' ],
            ['name' => 'Exness' ],
            ['name' => 'FBS' ],
            ['name' => 'FIBO Group' ],
            ['name' => 'Fidelity Investments' ],
            ['name' => 'Forex Club' ],
            ['name' => 'FOREX.com' ],
            ['name' => 'FP Markets' ],
            ['name' => 'FXCM' ],
            ['name' => 'FxGlory' ],
            ['name' => 'FXPrimus' ],
            ['name' => 'FxPro' ],
            ['name' => 'FXTM' ],
            ['name' => 'GMOTrading' ],
            ['name' => 'Grand Capital' ],
            ['name' => 'GSI Markets' ],
            ['name' => 'HotForex' ],
            ['name' => 'HYCM' ],
            ['name' => 'ICMarkets' ],
            ['name' => 'iForex' ],
            ['name' => 'IG ' ],
            ['name' => 'Interactive Brokers' ],
            ['name' => 'IQ Option' ],
            ['name' => 'LBLV' ],
            ['name' => 'LegacyFX' ],
            ['name' => 'LH Crypto' ],
            ['name' => 'Libertex' ],
            ['name' => 'LIGHTSPEED' ],
            ['name' => 'London Capital Group' ],
            ['name' => 'Markets.com' ],
            ['name' => 'Merrill Edge' ],
            ['name' => 'MetaQuotes Software Corp.' ],
            ['name' => 'MT4' ],
            ['name' => 'MT5' ],
            ['name' => 'MultiBank' ],
            ['name' => 'NinjaTrader' ],
            ['name' => 'Oanda' ],
            ['name' => 'OctaFX' ],
            ['name' => 'Olymp Trade' ],
            ['name' => 'Orbex' ],
            ['name' => 'Pepperstone' ],
            ['name' => 'Phillip Capital' ],
            ['name' => 'Plus500' ],
            ['name' => 'ProfitiX' ],
            ['name' => 'Robinhood' ],
            ['name' => 'Saxo Bank' ],
            ['name' => 'Sierra Futures' ],
            ['name' => 'Swissquote Bank' ],
            ['name' => 'Tastyworks' ],
            ['name' => 'TD Ameritrade ' ],
            ['name' => 'TradeStation' ],
            ['name' => 'Trading.com' ],
            ['name' => 'USGFX' ],
            ['name' => 'Valores Bancolombia' ],
            ['name' => 'VANGUARD' ],
            ['name' => 'X-TRADE BROKERS (XTB)' ],
            ['name' => 'XM Global Limited' ],
        ];

        foreach ($brokers as $broker) {
            \App\Broker::create($broker);
        }

        // TRADES
        Schema::dropIfExists('trades');
        Schema::create('trades', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->bigIncrements('id');
            $table->foreignId('user_id')->constrained();
            $table->foreignId('side_id')->constrained();
            $table->foreignId('strategy_id')->nullable()->constrained();
            $table->foreignId('mood_id')->nullable()->constrained();
            $table->foreignId('asset_id')->constrained();
            $table->foreignId('broker_id')->constrained()->nullable();
            $table->double('entry_price');
            $table->double('exit_price');
            $table->double('points')->default(0);
            $table->dateTime('trade_date')->nullable();
            $table->dateTime('entry_date')->nullable();
            $table->dateTime('exit_date')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
